Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  # Web Servers
  config.vm.define "web01" do |web01|
    web01.vm.network "private_network", ip: "192.168.50.101"
    web01.vm.hostname = "web01"
  end

  config.vm.define "web02" do |web02|
    web02.vm.network "private_network", ip: "192.168.50.102"
    web02.vm.hostname = "web02"
  end

  # Database Server
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.network "private_network", ip: "192.168.50.103"
    db01.vm.hostname = "db01"
  end
end
